server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/projects/practice
    driver-class-name: org.h2.Driver
    username: sa
    password: a

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true